spring:
  application:
    name: MapQuizzes
  datasource:
    url: jdbc:postgresql://localhost:5432/map_quizzes
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect